FROM ubuntu

WORKDIR /app

RUN sudo apt-get update
RUN sudo apt-get install python3-pip
RUN sudo apt-get install python3.10-venv
RUN python3 -m venv ./venv
RUN source ./venv/bin/activate
RUN pip3 install -U pip
RUN pip3 install tensorflow==2.7.0 --no-cache-dir
RUN pip3 install rasa

COPY rasa-chat/rasa-assistant /app

CMD ["rasa", "run", "--model", "./rasa-assistant/models/", "--enable-api", "--cors", "\"\*\""]