FROM ubuntu

WORKDIR /app

RUN apt-get update
RUN apt-get install -y python3-pip
RUN apt-get install -y python3.10-venv
RUN python3 -m venv ./venv
RUN . ./venv/bin/activate
RUN pip3 install -U pip
RUN pip3 install tensorflow --no-cache-dir
RUN pip3 install rasa

COPY rasa-chat/rasa-assistant /app

CMD ["rasa", "run", "--model", "./rasa-assistant/models/20230518-235803-relaxed-peak.tar.gz", "--enable-api", "--cors", "\"\*\""]