apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-manager-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: file-manager
  template:
    metadata:
      labels:
        app: file-manager
    spec:
      containers:
        - name: file-manager
          image: elgharabawi/file-manager
---
# apiVersion: v1
# kind: Service
# metadata:
#   name: file-manager-balancer
# spec: 
#   type: LoadBalancer
#   selector:
#     app: file-manager
#   ports:
#     - name: file-manager
#       protocol: TCP
#       port: 3002
#       targetPort: 3002
