apiVersion: apps/v1
kind: Deployment
metadata:
  name: rasa-chat-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rasa-chat
  template:
    metadata:
      labels:
        app: rasa-chat
    spec:
      containers:
        - name: rasa-chat
          image: elgharabawi/rasa-chat
---
apiVersion: v1
kind: Service
metadata:
  name: rasa-chat-service
spec:
  type: NodePort
  selector:
    app: rasa-chat
  ports:
    - protocol: TCP
      port: 5005
      targetPort: 5005
      nodePort: 8081

