apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-auth
  template:
    metadata:
      labels:
        app: users-auth
    spec:
      containers:
        - name: users-auth
          image: elgharabawi/users-auth
---
apiVersion: v1
kind: Service
metadata:
  name: users-auth-srv
spec:
  selector:
    app: users-auth
  ports:
    - name: users-auth
      protocol: TCP
      port: 3001
      targetPort: 3001