name: deploy-rasa-chat

on: 
  push:
    branches:
      - main
    paths:
      - 'rasa-chat/**'
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker build -t elgharabawi/rasa-chat -f Dockerfile.rasa-chat .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env: 
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push elgharabawi/rasa-chat
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save builtop
      - run: kubectl rollout restart deployment rasa-chat-depl