name: deploy-api-gateway

on: 
  push:
    branches:
      - main
    paths:
      - 'api-gateway/**'
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker build -t elgharabawi/api-gateway -f Dockerfile.api-gateway .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env: 
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push elgharabawi/api-gateway
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save builtop
      - run: kubectl rollout restart deployment api-gateway-depl